# Generated by Django 4.0.5 on 2022-06-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_todo_delete_article_delete_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Содержание задачи'),
        ),
    ]
